-- Phase 0-5 基盤実証用の初期マイグレーション。
-- スキーマは Flyway が所有する（JPA は ddl-auto=validate で検証のみ）。
-- Envers（変更履歴）を使うため、監査テーブル（*_aud）とリビジョン台帳（revinfo）も Flyway で作成する。

-- Envers のリビジョン台帳（1回の変更 = 1リビジョン）
create table revinfo (
    rev      bigint generated by default as identity primary key,
    revtstmp bigint
);

-- 基盤実証用のサンプルテーブル（実エンティティ導入時に置換・削除する）
create table sample_record (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null,
    created_at timestamptz  not null,
    updated_at timestamptz  not null
);

-- sample_record の変更履歴（Envers）
create table sample_record_aud (
    id         bigint   not null,
    rev        bigint   not null references revinfo (rev),
    revtype    smallint,
    name       varchar(255),
    created_at timestamptz,
    updated_at timestamptz,
    primary key (id, rev)
);
